config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # verb 'path', to: 'Controller#Action'
  # ALL the restaurant
  # get 'restaurants', to: 'restaurants#index'

  # # Write a restaurant divided in two steps:
  # # 1. NEW
  # get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant

  # # One restaurant
  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  # # DELETE a restaurant
  # delete 'restaurants/:id', to: 'restaurants#destroy'

  # # 2. CREATE
  # post 'restaurants', to: 'restaurants#create'

  # # UPDATE a restaurant
  # get 'restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant

  # patch 'restaurants/:id', to: 'restaurants#update'

  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to @restaurant
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)

    redirect_to @restaurant
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.button :submit, class: 'btn btn-primary w-100' %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>


<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %> -
      <%= link_to 'Edit', edit_restaurant_path(restaurant), class: 'btn btn-warning' %> -
      <%= link_to 'Delete',
                  restaurant_path(restaurant),
                  method: :delete,
                  class: 'btn btn-danger',
                  data: { confirm: "Are you sure ?" } %>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.address %> - <%= @restaurant.rating %></p>